Name : Testinette's Execution with Vitest
 on :
 push :

 permissions :
 content : writing

 jobs :
 execute-testinette :
 Works on : ubuntu-latest
 container :
 image : ghcr.io/ghcr.io/edenschoolfrance/exam_a1-1javascript:latest
 Identification information :
 username : ${{  github  .  actor  }}
 Password : ${{  secrets  .  github_token  }}
 volumes :
 - ${{ github . workspace }} :/app/src
 options : --cpus 1
 steps :
- Name : Consult the repository
 Uses : actions/checkout@v4
- Name : Remove optional export keyword
 exécuter : sed -i 's/export function/function/g' /app/src/*
- Name : Add an export keyword
 exécuter : sed -i 's/function/export function/g' /app/src/*
- Name : Test in progress
 Run : cd /app && npm run test
